# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/kovsky/extract-files.sh - DO NOT EDIT

# All the blobs necessary for kovsky
PRODUCT_COPY_FILES := \
    vendor/htc/kovsky/proprietary/brf6300.bin:system/etc/firmware/brf6300.bin \
    vendor/htc/kovsky/proprietary/brf6350.bin:system/etc/firmware/brf6350.bin \
    vendor/htc/kovsky/proprietary/wl1251-fw.bin:system/etc/firmware/wl1251-fw.bin \
    vendor/htc/kovsky/proprietary/wl1251-nvs.bin:system/etc/firmware/wl1251-nvs.bin \
    vendor/htc/kovsky/proprietary/libGLES_qcom.so:system/lib/egl/libGLES_qcom.so \
    vendor/htc/kovsky/proprietary/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/htc/kovsky/proprietary/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/htc/kovsky/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/htc/kovsky/proprietary/libcamera.so:system/lib/libcamera.so \
    vendor/htc/kovsky/proprietary/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/htc/kovsky/proprietary/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/htc/kovsky/proprietary/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
